name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run backend tests
        run: npm -w backend test
        env:
          CI: true

      - name: Build frontend
        run: npm -w frontend run build
        env:
          VITE_API_BASE: /api
          CI: true

      - name: Build backend
        run: npm -w backend run build
        env:
          CI: true
